### ISSUE TITLE
No Gyro for Matek F411 with BTFL >= 4.4.x

### ISSUE THREAD

**Issue by Gorlinux** [betaflight/unified-targets#1335] opened 2024-07-02 15:53 UTC
ID: "db50e483-4c0e-47b8-b33d-fe6733a6c20c"

**Comment by Gorlinux** [comment] 2024-07-02 15:56
Gyro works flawless with BTFL v4.3.2

**Comment by haslinghuis** [comment] 2024-07-02 16:01
Duplicate of #1333

**Closed by haslinghuis** 2024-07-02 16:01 UTC
