### ISSUE TITLE
Darwin fpv missing gyro after updating to BF 4.4.1

### ISSUE THREAD

**Issue by Psystick** [betaflight/unified-targets#1000] opened 2023-05-04 07:55 UTC
Missing motor output protocol, gyro/accelerometer for the Darwin FPV 15a 1-3s F411 ultralight whoop AIO on the BF 4.4.1 firmware 
Submitted the support data here's the Ticket 
Id: "7c069f70-23a6-4f41-a965-2367b6ab81ac

Missing motor output protocol is Dshot600 according to Darwin FPV 

The missing gyro/accelerometer is #define USE_GYRO_SPI_ICM20689
#define USE_ACC_SPI_ICM20689

Board name is: MATEKF411
Manufacturer id is : MTKS

I flashed my AIO to BF 4.4.1 saw the pop ups after applying defaults. I went back to the firmware flasher tab selected MATEKF411 as my target and 4.4.1 as my firmware THIS TIME selecting core only. 
After flashing a second time I went to the CLI tab submitted the support data and took a photo of the name of the gyro  and accelerometer.
I went to https://betaflight.com/docs/manufacturer/manufacturer-design-guidelines#42-definitions-for-targets and found the Gyro and ACC defines listed above.
Going back to flash for a 3rd time, but this time enabling "Show release candidates" and "Enable Expert Mode", selected the same target same firmware and plugging in GYRO_SPI_ICM20689 ACC_SPI_ICM20689 under the "Custom Defines" tab now my gyro is back.

Hope this helps.

**Comment by haslinghuis** [comment] 2023-05-04 08:58
Duplicate of https://github.com/betaflight/unified-targets/issues/832

**Closed by haslinghuis** 2023-05-04 08:58 UTC
