### ISSUE TITLE
Loss of gyro flashing 4.5

### ISSUE THREAD

**Issue by Clazyo** [betaflight/unified-targets#1336] opened 2024-07-07 18:09 UTC
Hi.
i have a DarwinFPV baby ape pro v2 with:
GYRO=MPU6500, ACC=MPU6500
And i tried to flash to the latest stable firmware 4.5 and my gyro did not respond. It works with Betaflight 4.2.11 running with bf-configurator 10.10.0.

Solution maybe:
add MPU6500 for the target:MATEKF411 into the new stable version of 4.5

Thanks for reading and thank you for making the most fun hobby possible :)

**Comment by haslinghuis** [comment] 2024-07-07 18:13
Try `DARWINF411` instead

**Comment by haslinghuis** [comment] 2024-07-07 18:47
Duplicate of #1333

**Closed by haslinghuis** 2024-07-07 18:47 UTC
